flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location:
    git: https://github.com/MarekSuchanek/hCM.git
    commit: 5f4155c668072116d5356df514c344295e9091f3
  extra-dep: true
extra-deps:
- dates-0.2.2.1
resolver: lts-8.12
